
\newpage
# Introdução

O objetivo do exercício será estimar uma forma reduzida da Curva de Phillips do Modelo Semiestrutural de Pequeno Porte do BCB (ver \href{https://www.bcb.gov.br/?RI201809B9P}{aqui}), conforme descrito abaixo:

\begin{align}
\pi_t^{livres} = \sum_{i>0} \beta_{1i} E_t \pi^{total}_{t+i} +\sum_{j>0} \beta_{2j} \pi^{total}_{t-j} +\sum_{k \geq 0} \beta_{3k} \pi^{importada}_{t-k} + \sum_{l>0} \beta_{4l} hiato_{t-l} + \sum_{m = 1}^4 D_m + \epsilon_t \label{cp}
\end{align} 

com a imposição da restrição de verticalidade de longo prazo:

\begin{align}
\sum_{i>0} \beta_{1i} +\sum_{j>0} \beta_{2j} +\sum_{k \geq 0} \beta_{3k} = 1
\end{align}

Basicamente, a inflação dos preços livres é uma função linear da **inflação passada**, das **expectativas de inflação**, do **hiato do produto** e da **inflação importada**. 

# Pacotes

Abaixo, carregamos os pacotes necessários para o exercício.^[O pacote `rbcb` não está mais disponível no CRAN, sendo necessário instalá-lo via `github` através do pacote `devtools`. Maiores detalhes, ver [aqui](https://github.com/wilsonfreitas/rbcb).]

\bigskip
